eureka:
  client:
    fetch-registry: true
    instance:
      hostname: localhost
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payments/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/orderPlaced  
